In [1]:
import pandas as pd
import numpy as np
from google.colab import files

print("Libraries imported successfully.")

print("Please upload your Excel dataset:")

uploaded = files.upload()

file_name = next(iter(uploaded))

print(f"\nFile uploaded successfully: {file_name}")


df = pd.read_excel(file_name)

print("\n" + "="*60)
print("DATASET LOADED")
print("="*60)

print(f"Number of rows    : {df.shape[0]}")
print(f"Number of columns : {df.shape[1]}")

print("\nFirst 5 rows:")
display(df.head())


print("\n" + "="*60)
print("INITIAL DATA INFORMATION")
print("="*60)

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nDataset information:")
df.info()

print("\n" + "="*60)
print("MISSING VALUES ANALYSIS")
print("="*60)

missing_count = df.isnull().sum()
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_summary = pd.DataFrame({
    "Missing Values": missing_count,
    "Missing Percentage": missing_percentage.round(2)
})

missing_summary = missing_summary[
    missing_summary["Missing Values"] > 0
].sort_values("Missing Values", ascending=False)

if missing_summary.empty:
    print("No missing values found.")
else:
    print("Missing values found:")
    display(missing_summary)




if "CouponCode" in df.columns:
    df["CouponCode"] = df["CouponCode"].fillna("No Coupon")

print("\n" + "="*60)
print("DUPLICATE ANALYSIS")
print("="*60)

duplicates_before = df.duplicated().sum()

print(f"Duplicate rows found: {duplicates_before}")

if duplicates_before > 0:
    df = df.drop_duplicates().reset_index(drop=True)
    print(f"Duplicate rows removed: {duplicates_before}")
else:
    print("No duplicate rows found.")


df.columns = (
    df.columns
    .str.strip()
    .str.replace(" ", "_")
)

text_columns = df.select_dtypes(include=["object"]).columns

for column in text_columns:
    df[column] = df[column].apply(
        lambda x: x.strip() if isinstance(x, str) else x
    )

print("\nText columns cleaned successfully.")


if "Date" in df.columns:
    df["Date"] = pd.to_datetime(
        df["Date"],
        errors="coerce"
    )

    print("Date column converted to datetime format.")

numeric_columns = [
    "Quantity",
    "UnitPrice",
    "ItemsInCart",
    "TotalPrice"
]

for column in numeric_columns:
    if column in df.columns:
        df[column] = pd.to_numeric(
            df[column],
            errors="coerce"
        )

print("Numeric columns converted successfully.")



standardize_columns = [
    "Product",
    "PaymentMethod",
    "OrderStatus",
    "CouponCode",
    "ReferralSource"
]

for column in standardize_columns:
    if column in df.columns:
        df[column] = df[column].apply(
            lambda x: " ".join(x.split()) if isinstance(x, str) else x
        )

print("\n" + "="*60)
print("MISSING VALUES AFTER CLEANING")
print("="*60)

remaining_missing = df.isnull().sum()

remaining_missing = remaining_missing[
    remaining_missing > 0
]

if remaining_missing.empty:
    print("No missing values remain.")
else:
    print("Remaining missing values:")
    display(remaining_missing)


print("\n" + "="*60)
print("DUPLICATES AFTER CLEANING")
print("="*60)

duplicates_after = df.duplicated().sum()

print(f"Remaining duplicate rows: {duplicates_after}")


print("\n" + "="*60)
print("FINAL DATA TYPES")
print("="*60)

display(
    pd.DataFrame({
        "Column": df.columns,
        "Data Type": df.dtypes.astype(str).values
    })
)


print("\n" + "="*60)
print("DATA QUALITY CHECKS")
print("="*60)

if "Quantity" in df.columns:
    negative_quantity = (df["Quantity"] < 0).sum()
    print(f"Negative Quantity values: {negative_quantity}")

if "UnitPrice" in df.columns:
    negative_price = (df["UnitPrice"] < 0).sum()
    print(f"Negative UnitPrice values: {negative_price}")


if "TotalPrice" in df.columns:
    negative_total = (df["TotalPrice"] < 0).sum()
    print(f"Negative TotalPrice values: {negative_total}")

if "Date" in df.columns:
    invalid_dates = df["Date"].isnull().sum()
    print(f"Invalid/Missing Date values: {invalid_dates}")

if all(col in df.columns for col in ["Quantity", "UnitPrice", "TotalPrice"]):

    calculated_total = (
        df["Quantity"] * df["UnitPrice"]
    ).round(2)

    price_mismatch = (
        calculated_total != df["TotalPrice"].round(2)
    ).sum()

    print(f"TotalPrice calculation mismatches: {price_mismatch}")

print("\n" + "="*60)
print("FINAL CLEAN DATASET SUMMARY")
print("="*60)

print(f"Rows before cleaning     : 1200")
print(f"Rows after cleaning      : {len(df)}")
print(f"Columns                  : {len(df.columns)}")
print(f"Duplicate rows remaining : {df.duplicated().sum()}")
print(f"Missing values remaining : {df.isnull().sum().sum()}")

print("\nFinal dataset preview:")
display(df.head())

output_file = "Cleaned_Dataset.xlsx"

df.to_excel(
    output_file,
    index=False
)

print("\n" + "="*60)
print("CLEANING COMPLETED")
print("="*60)

print(f"Cleaned dataset saved as: {output_file}")

files.download(output_file)

Libraries imported successfully.
Please upload your Excel dataset:

Saving Dataset for Data Analytics.xlsx to Dataset for Data Analytics.xlsx

File uploaded successfully: Dataset for Data Analytics.xlsx

============================================================
DATASET LOADED
============================================================
Number of rows    : 1200
Number of columns : 14

First 5 rows:

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

============================================================
INITIAL DATA INFORMATION
============================================================

Column names:
['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice', 'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber', 'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice']

Data types:
OrderID                    object
Date               datetime64[ns]
CustomerID                 object
Product                    object
Quantity                    int64
UnitPrice                 float64
ShippingAddress            object
PaymentMethod              object
OrderStatus                object
TrackingNumber             object
ItemsInCart                 int64
CouponCode                 object
ReferralSource             object
TotalPrice                float64
dtype: object

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

============================================================
MISSING VALUES ANALYSIS
============================================================
Missing values found:

            Missing Values  Missing Percentage
CouponCode             309               25.75

============================================================
DUPLICATE ANALYSIS
============================================================
Duplicate rows found: 0
No duplicate rows found.

Text columns cleaned successfully.
Date column converted to datetime format.
Numeric columns converted successfully.

============================================================
MISSING VALUES AFTER CLEANING
============================================================
No missing values remain.

============================================================
DUPLICATES AFTER CLEANING
============================================================
Remaining duplicate rows: 0

============================================================
FINAL DATA TYPES
============================================================

             Column       Data Type
0           OrderID          object
1              Date  datetime64[ns]
2        CustomerID          object
3           Product          object
4          Quantity           int64
5         UnitPrice         float64
6   ShippingAddress          object
7     PaymentMethod          object
8       OrderStatus          object
9    TrackingNumber          object
10      ItemsInCart           int64
11       CouponCode          object
12   ReferralSource          object
13       TotalPrice         float64

============================================================
DATA QUALITY CHECKS
============================================================
Negative Quantity values: 0
Negative UnitPrice values: 0
Negative TotalPrice values: 0
Invalid/Missing Date values: 0
TotalPrice calculation mismatches: 0

============================================================
FINAL CLEAN DATASET SUMMARY
============================================================
Rows before cleaning     : 1200
Rows after cleaning      : 1200
Columns                  : 14
Duplicate rows remaining : 0
Missing values remaining : 0

Final dataset preview:

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

============================================================
CLEANING COMPLETED
============================================================
Cleaned dataset saved as: Cleaned_Dataset.xlsx